---
# tasks file for idm_server
- name: Determine IDM server type
  set_fact:
    idm_server_type: >-
      {{ (
        'master' if inventory_hostname | regex_search('idm0?1(\..*)?$')
        else 'replica'
      ) | trim }}

- debug:
    msg: "Host {{ inventory_hostname }} will be treated as {{ idm_server_type }}"

- name: Include tasks for master
  include_tasks: master.yml
  when: idm_server_type == "master"

- name: Include tasks for replica
  include_tasks: replica.yml
  when: idm_server_type == "replica"
