- name: Enable IDM module
  ansible.builtin.command:
    cmd: dnf module enable -y idm:DL1
  args:
    creates: /etc/dnf/modules.d/idm.module

- name: Install IPA server packages
  package:
    name:
      - ipa-server
      - ipa-server-dns
    state: present

- name: Check if IPA master is already configured
  stat:
    path: /etc/ipa/default.conf
  register: ipa_config

- name: Install IPA server with DNS
  command: >
    ipa-server-install
      --domain {{ idm_domain }}
      --realm {{ idm_realm }}
      --ds-password {{ idm_ds_password }}
      --admin-password {{ idm_admin_password }}
      {% if idm_setup_dns | bool %}
      --setup-dns
      {% if idm_forwarders %}
      --forwarder {{ idm_forwarders | replace(',', ' --forwarder ') }}
      {% endif %}
      {% if idm_allow_zone_overlap | bool %}
      --allow-zone-overlap
      {% endif %}
      {% if idm_auto_reverse | bool %}
      --auto-reverse
      {% endif %}
      {% endif %}
      {% if idm_no_host_dns | bool %}
      --no-host-dns
      {% endif %}
      --unattended
  when: not ipa_config.stat.exists


- name: Enable and start IPA
  service:
    name: ipa
    state: started
    enabled: true

- name: Configure chrony for IDM
  block:
    - name: Ensure chrony is installed
      package:
        name: chrony
        state: present

    - name: Configure NTP servers
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server'
        line: "server {{ item }} iburst"
      loop: "{{ idm_ntp_servers.split(',') }}"
      when: idm_ntp_servers != ""
      notify:
        - Restart chrony
